# Generated by Django 4.2.23 on 2025-06-22 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('og_image', models.ImageField(blank=True, upload_to='uploads/', verbose_name='OpenGraph Image')),
                ('canonical_url', models.CharField(blank=True, max_length=255, verbose_name='Canonical URL')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('published_at', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('template', models.CharField(choices=[{'blue', 'Синий'}, {'Зеленый', 'green'}, {'Красный', 'red'}], max_length=50, verbose_name='Шаблон')),
                ('status', models.CharField(choices=[{'Открыто', 'opened'}, {'closed', 'Закрыто'}, {'В архиве', 'archived'}], max_length=50, verbose_name='Статус')),
            ],
        ),
    ]
