# Generated by Django 4.2.23 on 2025-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('opened', 'Открыто'), ('closed', 'Закрыто'), ('archived', 'В архиве')], max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='template',
            field=models.CharField(choices=[('blue', 'Синий'), ('green', 'Зеленый'), ('red', 'Красный')], max_length=50, verbose_name='Шаблон'),
        ),
    ]
