# Generated by Django 4.2.23 on 2025-06-22 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('og_image', models.ImageField(upload_to='uploads/')),
                ('canonical_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('published_at', models.DateField(default=datetime.date.today)),
                ('author', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('template', models.CharField(choices=[{'Синий', 'blue'}, {'green', 'Зеленый'}, {'Красный', 'red'}], max_length=50)),
                ('status', models.CharField(choices=[{'Открыто', 'opened'}, {'closed', 'Закрыто'}, {'archived', 'В архиве'}], max_length=50)),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.seo')),
            ],
        ),
    ]
